// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7BA1Ijxr0xGxLkAb8P0rCyE97_vG1KZk',
    appId: '1:437331066450:web:a80e611146f912a402298b',
    messagingSenderId: '437331066450',
    projectId: 'air-hockey-project',
    authDomain: 'air-hockey-project.firebaseapp.com',
    storageBucket: 'air-hockey-project.appspot.com',
    measurementId: 'G-QYX5W3ZWG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPtjPf2o3aqxRVBBeejFO7xoBVYgV1as8',
    appId: '1:437331066450:android:0a93e01cfb5d471f02298b',
    messagingSenderId: '437331066450',
    projectId: 'air-hockey-project',
    storageBucket: 'air-hockey-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_F_yCWrDKPWyTUKwvbUqc8MzQrbEJvaw',
    appId: '1:437331066450:ios:158aa2e615ba798202298b',
    messagingSenderId: '437331066450',
    projectId: 'air-hockey-project',
    storageBucket: 'air-hockey-project.appspot.com',
    iosBundleId: 'com.example.airhockey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_F_yCWrDKPWyTUKwvbUqc8MzQrbEJvaw',
    appId: '1:437331066450:ios:158aa2e615ba798202298b',
    messagingSenderId: '437331066450',
    projectId: 'air-hockey-project',
    storageBucket: 'air-hockey-project.appspot.com',
    iosBundleId: 'com.example.airhockey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7BA1Ijxr0xGxLkAb8P0rCyE97_vG1KZk',
    appId: '1:437331066450:web:d2758ace46aacef102298b',
    messagingSenderId: '437331066450',
    projectId: 'air-hockey-project',
    authDomain: 'air-hockey-project.firebaseapp.com',
    storageBucket: 'air-hockey-project.appspot.com',
    measurementId: 'G-7WV37VGBWP',
  );
}
